# Generated by Django 3.0.7 on 2022-04-10 02:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_time', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.Journey')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.Quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quest', 'journey')},
            },
        ),
    ]
